# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAMIFbw4Y4NXgr0yY3SW7fTHAL7U0AvM
"""

# app.py
from flask import Flask, request, jsonify
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
import joblib

app = Flask(__name__)

# Cargar modelo y scaler
model = load_model('modelo_lstm.h5')
scaler = joblib.load('scaler.save')

# Ruta para prediccion
@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.json['data']  # Se espera una lista de 24 valores
        if len(data) != 24:
            return jsonify({'error': 'Se requieren exactamente 24 valores'}), 400

        # Preprocesamiento de entrada
        input_scaled = scaler.transform(np.array(data).reshape(-1, 1))
        input_reshaped = np.reshape(input_scaled, (1, 24, 1))

        # Prediccion
        pred_scaled = model.predict(input_reshaped)
        pred = scaler.inverse_transform(pred_scaled)

        return jsonify({'prediccion': round(float(pred[0, 0]), 3)})

    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)